### ISSUE TITLE
Enter 0  sign up WTF??

### ISSUE THREAD

**Issue by dreamooo** [k1tsanapong/SteamReplit#25]
แก้ให้ Enter  0   ใน sign up ให้ดีเหมือน log in

**Comment by dreamooo** [comment]
BUGGGGG    
หน้า top up   มี บัค  ถ้าเรากดเลข นอกเหนือจาก  1 หรือ 0    loop WTF

**Comment by dreamooo** [comment]
หน้า shop    กดเลข อื่น นอกจาก 0 1 2 3 45   มันไม่ขึ้น  เตือน  pls select  only

**Comment by k1tsanapong** [comment]
fixed
